// Re-export the most-used Prisma types under a stable path for app code.
export type {
  User,
  Address,
  Product,
  ProductImage,
  ProductVariant,
  Category,
  Cart,
  CartItem,
  Order,
  OrderItem,
  OrderShipping,
  Payment,
  Discount,
  BlogPost,
  Testimonial,
  Review,
  NewsletterSubscriber,
  ContactMessage,
  Wishlist,
  StockMovement,
} from '@prisma/client';

export {
  UserRole,
  ProductStatus,
  OrderStatus,
  PaymentStatus,
  PaymentMethod,
  DiscountType,
  DiscountStatus,
  DiscountApplyTarget,
  CustomerScope,
  ContentStatus,
  ReviewStatus,
  SubscriptionStatus,
  OtpPurpose,
  StockChangeReason,
} from '@prisma/client';
